// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTransportationApp.Data;

#nullable disable

namespace MyTransportationApp.Migrations
{
    [DbContext(typeof(MyTransportationAppContext))]
    partial class MyTransportationAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyTransportationApp.Models.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.ToTable("City");
                });

            modelBuilder.Entity("MyTransportationApp.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("MyTransportationApp.Models.Stop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("Stop");
                });

            modelBuilder.Entity("MyTransportationApp.Models.Train", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TrainCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransporterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TransporterID");

                    b.ToTable("Train");
                });

            modelBuilder.Entity("MyTransportationApp.Models.Transporter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("TransporterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.ToTable("Transporter");
                });

            modelBuilder.Entity("MyTransportationApp.Models.Vehicle", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransporterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TransporterID");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("MyTransportationApp.Models.City", b =>
                {
                    b.HasOne("MyTransportationApp.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryID");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MyTransportationApp.Models.Stop", b =>
                {
                    b.HasOne("MyTransportationApp.Models.City", "City")
                        .WithMany("Stops")
                        .HasForeignKey("CityID");

                    b.Navigation("City");
                });

            modelBuilder.Entity("MyTransportationApp.Models.Train", b =>
                {
                    b.HasOne("MyTransportationApp.Models.Transporter", "Transporter")
                        .WithMany("Train")
                        .HasForeignKey("TransporterID");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("MyTransportationApp.Models.Transporter", b =>
                {
                    b.HasOne("MyTransportationApp.Models.Country", "Country")
                        .WithMany("Transporters")
                        .HasForeignKey("CountryID");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MyTransportationApp.Models.Vehicle", b =>
                {
                    b.HasOne("MyTransportationApp.Models.Transporter", "Transporter")
                        .WithMany("Vehicle")
                        .HasForeignKey("TransporterID");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("MyTransportationApp.Models.City", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("MyTransportationApp.Models.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Transporters");
                });

            modelBuilder.Entity("MyTransportationApp.Models.Transporter", b =>
                {
                    b.Navigation("Train");

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
